### ISSUE TITLE
Questions about how to use veramo cli

### ISSUE THREAD

**Issue by cbw1030** [veramolabs/agent-explorer#65]
Hello, I'm currently running an agent with veramo cli.
I have some questions.

1. The link below tells us to write agent scheme to connect agent.
What is the meaning of agent system and where can I find it?
https://explore.veramo.dev/connect

2. How can I make a personal wallet in veramo cli?
3. You can create a public key through the 'veramo did add-key' command, what is the meaning of this public key and how can I get a private key that matches that key?

Thanks for taking time out from your busy schedule.

**Comment by mirceanis** [comment]
I'm closing this since there's an identical discussion in https://github.com/uport-project/veramo/discussions/657
